import streamlit as st
import yfinance as yf
from ta.momentum import RSIIndicator
from ta.trend import EMAIndicator
from fpdf import FPDF
import pandas as pd

# --- 1. SETUP & CONFIG ---
st.set_page_config(page_title="Institutional AI Agent", layout="wide")
st.title("🤖 AI Investment Principal Agent")

# --- 2. THE PDF GENERATOR (New Feature) ---
def create_pdf_report(ticker, data, report_text):
    # Initialize PDF
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # Title
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt=f"Investment Memo: {ticker}", ln=True, align='C')
    pdf.ln(10) # Line break
    
    # Metrics Table Section
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="KEY METRICS:", ln=True)
    
    pdf.set_font("Arial", size=12)
    # Note: We use 'Rs.' instead of '₹' because standard PDF fonts struggle with the Rupee symbol
    pdf.cell(200, 10, txt=f"Current Price: Rs. {data['price']}", ln=True)
    pdf.cell(200, 10, txt=f"Trend Status: {data['trend']}", ln=True)
    pdf.cell(200, 10, txt=f"RSI (Momentum): {data['rsi']:.2f}", ln=True)
    pdf.cell(200, 10, txt=f"P/E Ratio: {data['pe']}", ln=True)
    pdf.ln(10)
    
    # The Analysis Text
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="PRINCIPAL'S VERDICT:", ln=True)
    
    pdf.set_font("Arial", size=12)
    # multi_cell handles text wrapping automatically
    pdf.multi_cell(0, 10, txt=report_text)
    
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 10, txt="Generated by AI Investment Agent. Not financial advice.", align='C')
    
    # Return the PDF as a byte string (so the browser can download it)
    return pdf.output(dest='S').encode('latin-1')

# --- 3. THE ANALYST ENGINE ---
def analyze_stock(ticker):
    stock = yf.Ticker(ticker)
    df = stock.history(period="1y")
    if df.empty: return None, None
    
    # Indicators
    rsi = RSIIndicator(close=df["Close"], window=14).rsi().iloc[-1]
    ema = EMAIndicator(close=df["Close"], window=200).ema_indicator().iloc[-1]
    current_price = df["Close"].iloc[-1]
    
    # Logic
    trend = "BULLISH" if current_price > ema else "BEARISH"
    pe = stock.info.get('trailingPE', 0)
    
    return {
        "price": round(current_price, 2),
        "trend": trend,
        "rsi": rsi,
        "pe": pe
    }, df

def get_ai_verdict(data):
    # Simulating the AI response for this example
    return f"""
    Based on the current technical setup, {data['trend']} trend suggests strength. 
    However, with an RSI of {data['rsi']:.1f}, momentum is crucial to watch.
    The valuation at {data['pe']}x P/E indicates the stock is fairly priced.
    
    RECOMMENDATION: HOLD for better entry.
    """

# --- 4. THE DASHBOARD UI ---
with st.sidebar:
    st.header("Settings")
    ticker_input = st.text_input("Ticker Symbol:", value="RELIANCE.NS")
    run_btn = st.button("Run Analysis", type="primary")

if run_btn:
    with st.spinner(f"Analyzing {ticker_input}..."):
        metrics, history = analyze_stock(ticker_input)
        
        if metrics:
            # Show Metrics
            c1, c2, c3 = st.columns(3)
            c1.metric("Price", f"₹{metrics['price']}")
            c2.metric("Trend", metrics['trend'])
            c3.metric("RSI", f"{metrics['rsi']:.1f}")
            
            # Show Chart
            st.line_chart(history['Close'])
            
            # Generate Report Text
            report_text = get_ai_verdict(metrics)
            st.info(f"📝 **Memo:**\n{report_text}")
            
            # --- THE DOWNLOAD BUTTON ---
            # We generate the PDF bytes right here
            pdf_data = create_pdf_report(ticker_input, metrics, report_text)
            
            st.download_button(
                label="📄 Download PDF Report",
                data=pdf_data,
                file_name=f"{ticker_input}_Report.pdf",
                mime="application/pdf"
            )
            
        else:
            st.error("Ticker not found.")
        