import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go
from ta.momentum import RSIIndicator
from ta.trend import EMAIndicator, MACD
from ta.volatility import BollingerBands
from fpdf import FPDF

# --- 1. PAGE CONFIG ---
st.set_page_config(page_title="Principal AI Agent", layout="wide")

# --- 2. USER DATABASE ---
USERS = {
    "admin": {"password": "Orbittal2025", "role": "admin", "name": "Principal Consultant"},
    "client": {"password": "guest", "role": "viewer", "name": "Valued Client"}
}

# --- 3. SECURITY SYSTEM ---
def check_login():
    if "logged_in" not in st.session_state:
        st.session_state["logged_in"] = False
        st.session_state["user_role"] = None
    
    if not st.session_state["logged_in"]:
        st.title("🔒 Institutional Login")
        c1, c2 = st.columns(2)
        with c1:
            user = st.text_input("Username")
            pwd = st.text_input("Password", type="password")
            if st.button("Login"):
                if user in USERS and USERS[user]["password"] == pwd:
                    st.session_state["logged_in"] = True
                    st.session_state["user_role"] = USERS[user]["role"]
                    st.session_state["user_name"] = USERS[user]["name"]
                    st.rerun()
                else:
                    st.error("Invalid Credentials")
        st.stop()

check_login()

# --- 4. ADVANCED ANALYTICS ENGINE ---
@st.cache_data(ttl=24*3600)
def analyze_stock(ticker):
    try:
        stock = yf.Ticker(ticker)
        df = stock.history(period="1y")
        if df.empty: return None, None, None
        
        # Technical Indicators
        rsi = RSIIndicator(close=df["Close"], window=14).rsi().iloc[-1]
        ema = EMAIndicator(close=df["Close"], window=200).ema_indicator().iloc[-1]
        
        macd = MACD(close=df["Close"])
        df['MACD'] = macd.macd()
        df['MACD_Signal'] = macd.macd_signal()
        current_macd = df['MACD'].iloc[-1]
        current_signal = df['MACD_Signal'].iloc[-1]
        
        bb = BollingerBands(close=df["Close"], window=20)
        df['BB_High'] = bb.bollinger_hband()
        df['BB_Low'] = bb.bollinger_lband()
        
        current_price = df["Close"].iloc[-1]
        
        # Fundamentals
        info = stock.info
        fundamentals = {
            "Market Cap": info.get('marketCap', 'N/A'),
            "52W High": info.get('fiftyTwoWeekHigh', 0),
            "P/E Ratio": info.get('trailingPE', 0),
        }
        
        # Scoring
        score = 0
        if current_price > ema: score += 1
        if 30 < rsi < 70: score += 1
        if current_macd > current_signal: score += 1
        
        metrics = {
            "price": round(current_price, 2),
            "trend": "BULLISH 🟢" if current_price > ema else "BEARISH 🔴",
            "rsi": round(rsi, 2),
            "macd_signal": "Buy Signal" if current_macd > current_signal else "Sell Signal",
            "score": score
        }
        
        return metrics, df, fundamentals
        
    except Exception as e:
        return None, None, None

# --- 5. PLOTLY CHARTING ---
def plot_advanced_chart(df, ticker):
    fig = go.Figure()
    fig.add_trace(go.Candlestick(x=df.index, open=df['Open'], high=df['High'], low=df['Low'], close=df['Close'], name='Price'))
    fig.add_trace(go.Scatter(x=df.index, y=df['BB_High'], line=dict(color='gray', width=1), name='BB Upper'))
    fig.add_trace(go.Scatter(x=df.index, y=df['BB_Low'], line=dict(color='gray', width=1), name='BB Lower'))
    fig.update_layout(title=f"{ticker} - Interactive Analysis", xaxis_rangeslider_visible=False, height=500)
    return fig

# --- 6. PDF GENERATOR (NOW WITH SANITIZER!) ---
def create_pdf(ticker, data, text):
    # Step 1: Clean the data (Remove Emojis and Rupee Symbols)
    clean_trend = data['trend'].replace("🟢", "").replace("🔴", "").strip()
    clean_price = str(data['price']).replace("₹", "Rs. ")
    
    # Step 2: Clean the main text (Force standard characters)
    # This replaces any unknown character with a '?' to prevent crashing
    clean_text = text.encode('latin-1', 'replace').decode('latin-1')
    
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # Title
    pdf.cell(200, 10, txt=f"Executive Brief: {ticker}", ln=True, align='C')
    pdf.ln(10)
    
    # Key Stats (Using Cleaned Data)
    pdf.cell(200, 10, txt=f"Price: Rs. {clean_price} | Trend: {clean_trend}", ln=True)
    pdf.cell(200, 10, txt=f"MACD Signal: {data['macd_signal']}", ln=True)
    pdf.ln(10)
    
    # Main Verdict (Using Cleaned Text)
    pdf.multi_cell(0, 10, txt=clean_text)
    
    # Footer
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 8)
    pdf.multi_cell(0, 5, txt="Generated by AI Agent. Not Financial Advice. Emojis removed for compatibility.")
    
    return pdf.output(dest='S').encode('latin-1')

# --- 7. DASHBOARD UI ---
st.title(f"📊 Institutional Dashboard ({st.session_state['user_name']})")

with st.sidebar:
    st.header("Controls")
    if st.session_state["user_role"] == "admin":
        mode = st.radio("Mode:", ["Deep Dive", "Competitor Comparison"])
    else:
        mode = st.radio("Mode:", ["Deep Dive"])
    
    if st.button("Logout"):
        st.session_state["logged_in"] = False
        st.rerun()

# === MODE 1: DEEP DIVE ===
if mode == "Deep Dive":
    st.subheader("🔍 Advanced Technical Analysis")
    ticker = st.text_input("Ticker Symbol:", value="RELIANCE.NS")
    
    if st.button("Analyze"):
        with st.spinner("Calculating Advanced Indicators..."):
            metrics, history, funds = analyze_stock(ticker)
            
            if metrics:
                k1, k2, k3, k4 = st.columns(4)
                k1.metric("Current Price", f"₹{metrics['price']}")
                k2.metric("Trend (200 EMA)", metrics['trend'])
                k3.metric("RSI Strength", metrics['rsi'])
                k4.metric("MACD Signal", metrics['macd_signal'])
                
                st.plotly_chart(plot_advanced_chart(history, ticker), use_container_width=True)
                
                c1, c2 = st.columns([1, 2])
                with c1:
                    st.markdown("### 🏢 Fundamentals")
                    st.dataframe(pd.DataFrame([funds]).T, height=200)
                
                with c2:
                    st.markdown("### 🤖 AI Executive Summary")
                    verdict = (f"{ticker} is currently in a {metrics['trend']} setup. "
                               f"RSI is at {metrics['rsi']}, indicating the stock is {'overbought' if metrics['rsi']>70 else 'neutral'}. "
                               f"Our MACD momentum indicator suggests a {metrics['macd_signal']}.")
                    st.info(verdict)
                    
                    # Call the SAFE PDF generator
                    pdf = create_pdf(ticker, metrics, verdict)
                    st.download_button("📄 Download Brief", data=pdf, file_name=f"{ticker}_Brief.pdf", mime="application/pdf")

# === MODE 2: COMPARISON ===
elif mode == "Competitor Comparison":
    st.subheader("⚖️ Quick Benchmarking")
    c1, c2 = st.columns(2)